### ISSUE TITLE
Examples don't work (Failed to execute /server: No such file or directory)

### ISSUE THREAD

**Issue by delneg** [unikraft/catalog#136] opened 2024-09-20 23:02 UTC
System: Darwin 23.4, arm64, M1 Max

What I did:
```
git clone https://github.com/unikraft/catalog unikraft-catalog
cd unikraft-catalog/examples/http-rust1.75/
kraft run --rm -p 8080:8080 --plat qemu --arch x86_64 .


 W  using hardware emulation
[+] building rootfs via Dockerfile... done!                                                                                                                                    x86_64 [1m 10s]
en1: Interface is up
en1: Set IPv4 address 10.0.2.15 mask 255.255.255.0 gw 10.0.2.2
Powered by Unikraft Calypso (0.17.0~62132e5)
[    1.116247] ERR:  [appelfloader] server: Failed to execute /server: No such file or directory
```

Also the same with Go example.

**Comment by mkroening** [comment] 2024-09-21 12:39
This is a duplicate of https://github.com/unikraft/catalog/issues/134.

**Closed by mkroening** 2024-09-21 12:39 UTC
